version: "3"
services:
  zookeeper:
    image: wurstmeister/zookeeper:3.4.6
    ports:
      - "2181:2181"
  kafka:
    image: wurstmeister/kafka:latest
    ports:
      - "9092:9092"
    environment:
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://localhost:9092
      KAFKA_LISTENERS: PLAINTEXT://0.0.0.0:9092
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: PLAINTEXT:PLAINTEXT
      KAFKA_INTER_BROKER_LISTENER_NAME: PLAINTEXT
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_CREATE_TOPICS: "user-profile-updates:1:1"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock

  service-a:
    image: vimigo/service-a:latest
    build:
      context: ./service-a
    ports:
      - "8081:8081"
    depends_on:
      - kafka

  service-b:
    image: vimigo/service-b:latest
    build:
      context: ./service-b
    ports:
      - "8082:8082"
    depends_on:
      - kafka

  service-c:
    image: vimigo/service-c:latest
    build:
      context: ./service-c
    ports:
      - "8083:8083"
    depends_on:
      - kafka

  api-gateway:
    image: vimigo/api-gateway:latest
    build:
      context: ./api-gateway
    ports:
      - "8080:8080"
